### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by wfajriansyahh** [fadhiilrachman/line-py#11]
Hello, i have a problem.
I use code, this:

> # -*- coding: utf-8 -*-
> from linepy import *
> 
> client = LineClient()
> #client = LineClient(authToken='AUTHTOKEN')
> 
> client.log("Auth Token : " + str(client.authToken))

Then, i got result Internal Error :

> akad.ttypes.TalkException: TalkException(parameterMap=None, reason=u'Internal error', code=20)

How?

**Comment by fadhiilrachman** [comment]
Update akad from pip with this:
`pip install akad==0.10.13`

**Comment by wfajriansyahh** [comment]
I have tried that, and response still 

> akad.ttypes.TalkException: TalkException(parameterMap=None, reason=u'Internal error', code=20)

**Comment by wfajriansyahh** [comment]
Solved, my ip is banned from line~
