### ISSUE TITLE
'Client' object has no attribute 'findGroupByTicket'

### ISSUE THREAD

**Issue by GoneawayCherry** [fadhiilrachman/line-py#13]
When I try:
client.findGroupByTicket(ID)

**Comment by HelloTan** [comment]
[2018-01-05 10:15:38.071735] 'Client' object has no attribute 'findGroupByTicket'

How to fix??

**Comment by wfajriansyahh** [comment]
Can you show your code ?

**Comment by fadhiilrachman** [comment]
This issue has been fixed. Please update linepy to version 1.9.5, follow this command:
`pip install linepy --upgrade`

**Comment by GoneawayCherry** [comment]
ok , It's my fault sorry, and I should have noticed earlier that my TalkService.py does not qualify for line-py

**Comment by GoneawayCherry** [comment]
@fadhiilrachman 
After updating, I use the same method but got None
I found that line 1514 of TalkService.py (in findGroupByTicket()) did not **return self.recv_findGroupByTicket ()**

**Comment by fadhiilrachman** [comment]
Fixed now, update the akad package (store LINE protocol) from pip, pip install akad --upgrade
