### ISSUE TITLE
Can't Login with mail and password

### ISSUE THREAD

**Issue by Dosugamea** [fadhiilrachman/line-py#16]
> Input this PIN code '7739' on your LINE for smartphone in 2 minutes
Traceback (most recent call last):
  File "...linepy\auth.py", line 123, in login
    'e2eeVersion': 0
  File "...linepy\auth.py", line 48, in loginRequest
    if data['identityProvider']:
KeyError: 'identityProvider'

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    cl = LineClient(id=mail,passwd=password)
  File "...linepy\client.py", line 26, in _init_
    self.login(_id=id, passwd=passwd, certificate=certificate, systemName=systemName, appName=appName, keepLoggedIn=keepLoggedIn)
  File "...linepy\auth.py", line 127, in login
    raise Exception("Login failed")
Exception: Login failed

When I login with email and password, these error happen.
Would you please fix it?

I tested with Python 3.6.4, akad 0.10.21, and line-py 2.0.1.

**Comment by fadhiilrachman** [comment]
We have fix several bugs, please update to newest version of linepy:
`pip install linepy --upgrade`

**Comment by Dosugamea** [comment]
It works!
Thank you for quick fix!
