### ISSUE TITLE
errorCode=0 when using getSquare()

### ISSUE THREAD

**Issue by y0r124** [fadhiilrachman/line-py#19]
I got this error, when I try to use getSquare, or getJoinableSquareChats.
> SquareException(errorCode=0, reason=u'An unknown error occurred. Please try again later.', errorExtraInfo=None)

getJoinedSquares() is fine and returning correct result.

I tried using this code :
`print client.getJoinableSquareChats(mid, limit=3)`

already tried to fill mid with user mid or square mid, but get the same result

am I using wrong format or I miss something somewhere?

**Comment by fadhiilrachman** [comment]
Are the square is public square or private square?

**Comment by y0r124** [comment]
I guess private square, because member can join if approved by admin (I guess i'll test if i make it public?)

**Comment by fadhiilrachman** [comment]
I've getting fix for this issue, next update will be available.
Thank you for your report

**Comment by y0r124** [comment]
Thank you, and thanks for your great job with this.

**Comment by fadhiilrachman** [comment]
Please upgrade linepy to newest version
`pip install linepy --upgrade`
