### ISSUE TITLE
can't use findAndAddContactsByMid(mid)

### ISSUE THREAD

**Issue by kaoru-nishida** [fadhiilrachman/line-py#22]
define findAndAddContactsByMid(self, reqSeq, mid, type, reference) in TalkService
But uses self.talk.findAndAddContactsByMid(0, mid) in client.py
So i got error
`findAndAddContactsByMid() missing 2 required positional arguments: 'type' and 'reference'`
Please fix this

**Comment by kaoru-nishida** [comment]
I fixed that by my self
in talk.py
`self.talk.findAndAddContactsByMid(0, mid)`
to
`self.talk.findAndAddContactsByMid(0, mid,5,"")`

**Comment by fadhiilrachman** [comment]
Bug fixed, thank you for your report.
Please upgrade for get newest version of linepy
`pip install linepy --upgrade`
