### ISSUE TITLE
Error When Logging

### ISSUE THREAD

**Issue by xprojectind** [fadhiilrachman/line-py#27]
[2018-01-19 17:37:18.940952] Your LINE account is not support Square
And 
akad.ttypes.ChannelException: ChannelException(parameterMap=None, reason='REVOKE', code=3)

**Comment by moepoi** [comment]
Takdir 😂

**Comment by Dewamade** [comment]
Already try upgrade akad?

**Comment by HelloTan** [comment]
Waiting 1 days

**Comment by xprojectind** [comment]
thanks for solution

**Comment by xprojectind** [comment]
Im can't login with qr , and i get messsage error
akad.ttypes.TalkException: TalkException(code=20, reason='Internal error', parameterMap=None)
Can you give me solution?
