### ISSUE TITLE
how to use createChatRoomAnnouncement?

### ISSUE THREAD

**Issue by ervan0707** [fadhiilrachman/line-py#29]
i try with createChatRoomAnnouncement(grup id,0,'teks')
but its say  'str' object has no attribute 'write', any solution for this?

**Comment by Dosugamea** [comment]
Here is one example. 
> from akad.ttypes import ChatRoomAnnouncementContents
> gid = "GroupID"
> an = ChatRoomAnnouncementContents(displayFields=5,text="Hello World",link="",thumbnail=None)
> cl.createChatRoomAnnouncement(gid,0,an)

Also, I'll make some examples at [here](https://github.com/Dosugamea/l-api-tips) later.
I hope it will be helpful to you.
