### ISSUE TITLE
SINGLETRACE ERROR

### ISSUE THREAD

**Issue by ervan0707** [fadhiilrachman/line-py#37]
i use single trace, sometimes i got error like this, ramdomly, wht should i do?
![image](https://user-images.githubusercontent.com/32308373/36127884-27850a12-1092-11e8-855f-d29e1a7f5989.png)

**Comment by crash-override404** [comment]
if ops != None:
    for op in ops:
        #Continue

**Comment by crash-override404** [comment]
Oh why indentation not working -_-

**Comment by ervan0707** [comment]
oh ahaha thx dude
