### ISSUE TITLE
Update profile error

### ISSUE THREAD

**Issue by Noxturnix** [fadhiilrachman/line-py#55]
client.updateProfileAttribute(8,pictureStatus)
give me TalkException error.

**Comment by Noxturnix** [comment]
It seems to have errors when you try to update your profile (name, status message, profile picture, cover picture).

**Comment by yuhei** [comment]
picturestatus is bad.
if you can , try delete it.
----------------------------------------
picturestatusが原因だそうです。
私にも訪れたので、picturestatusを消してみました、すると成功しました。
linepyのアップデートを待てないなら試してはいかがでしょうか。

**Comment by Noxturnix** [comment]
Thanks, I try to update profile picture using another method. Now I can update profile without any problem.
