### ISSUE TITLE
addfrienderror

### ISSUE THREAD

**Issue by arasi27676271** [fadhiilrachman/line-py#58]
when someone add me I use findAndAddContactsByMid(op.param1) to add him , and this is successful but when I want to send some notify message to him , and it is error, and system give an error message to me like this 

> [2018-06-08 09:10:50.346069] TalkException(code=82, reason='can not send using plain mode', parameterMap=None)

does anyone know how to fix it???
thx!!!

**Comment by mseric** [comment]
Unchecked the Letter Sealing in Privacy Settings in LINE app, then try again.

**Comment by arasi27676271** [comment]
yeah......I forget to shut it down haha  thank you
