### ISSUE TITLE
stop responding from user input

### ISSUE THREAD

**Issue by lintangtimur** [fadhiilrachman/line-py#6]
```python
while True:
    poll.trace()
```
5 minutes is working, but next minutes cant respond from user input.
like when i send to bot, its always autoread, but sometimes is not autoread

**Comment by fadhiilrachman** [comment]
Can you provide traceback result?

**Comment by lintangtimur** [comment]
there is no traceback result

**Comment by lintangtimur** [comment]
@fadhiilrachman this is what i get, bot is not response
![alt text](https://image.ibb.co/i0tjVG/selfbot_error.png"Error")
