### ISSUE TITLE
after 12-15h of running nothing happend

### ISSUE THREAD

**Issue by LifeBasher** [fadhiilrachman/line-py#85]
I'm not sure why but after like 12h - 15h of running, then whatever i do next isn't reported to the code anymore.....
any Idea?
Thanks

**Comment by asifjamali83** [comment]
How to install it in termux
Will you please indify it more easy
I'll appreciate you
Ty

**Comment by LifeBasher** [comment]
> How to install it in termux
> Will you please indify it more easy
> I'll appreciate you
> Ty

what do you mean? identify my problem or identify how to run line-py?

**Comment by asifjamali83** [comment]
Yes Basher bro

**Comment by LifeBasher** [comment]
> Yes Basher bro

which one..... it's a question with a choice.... you can't answer yes......

**Comment by asifjamali83** [comment]
Aslam o Alekum 
Bro I was thinking it's kicker bot , or group protect bot
Will you please suggest me any script 
I'll appreciate and thanks full to u
