### ISSUE TITLE
Account is broken after using API

### ISSUE THREAD

**Issue by pjc0247** [fadhiilrachman/line-py#87]
Hi, I made a bot which never sends any message. (just receiving)

After some works, I noticed that my account is broken.

My messages are not delivered to opponents at all even there's no error.
This is weird because I sent messages from official LINE clients (both desktop and mobile).

Everything except sending works fine.

Is this a ban? 
Does anybody experienced same issue?

**Comment by pjc0247** [comment]
If this is a ban, What's the best delay between `fetchOp` calls

**Comment by moonoiza** [comment]
I have faced this problem too.
I think Naver uses some technique to detect bots's behavior even they don't send out any messages.

**Comment by lintangtimur** [comment]
@moonoiza yes, its ban. Or you can just change that header

**Comment by moonoiza** [comment]
@lintangtimur Could you please give me more info which headers should be changed ? I have tried changing some auth headers like version , device name before but it didn't work.

**Comment by LifeBasher** [comment]
yep when you connect with old config header u get ban so u can read but if you send message, only you will see it and u cant join new channel either

**Comment by pjc0247** [comment]
In my case, I requested deprecated APIs. and it perfectly works even if deprecated. 
It's pretty dangerous to create a public app with these kinds of unofficial line APIs. LINE keep changing their protocols, but unofficial API doesn't

**Comment by LifeBasher** [comment]
> In my case, I requested deprecated APIs. and it perfectly works even if deprecated.
> It's pretty dangerous to create a public app with these kinds of unofficial line APIs. LINE keep changing their protocols, but unofficial API doesn't

it might be dangerous but you have acces to more stuff than the official bot :P lol
