### ISSUE TITLE
cannot login using token 

### ISSUE THREAD

**Issue by lanryryan** [fadhiilrachman/line-py#96]
Cannot login using token
How exactly i should do?

Code:
<img width="777" alt="line_login_code" src="https://user-images.githubusercontent.com/10055405/82543260-d5e91780-9b85-11ea-903e-068671196cc8.png">

Feadback:
<img width="901" alt="line" src="https://user-images.githubusercontent.com/10055405/82542905-5bb89300-9b85-11ea-9bcb-0a3af86b2cd9.png">

**Comment by shavy4452** [comment]
I am getting same. Got any solution?
